layouts:
  - row
  - bsp

mod1:
  - command

mod2:
  - shift
  - command

cycle-layout:
  mod: mod2
  key: l

cycle-layout-backward:
  mod: <NONE>
  key: <NONE>

shrink-main:
  mod: mod1
  key: h

expand-main:
  mod: mod1
  key: l

increase-main:
  mod: <NONE>
  key: <NONE>

decrease-main:
  mod: <NONE>
  key: <NONE>

focus-ccw:
  mod: mod1
  key: k

focus-cw:
  mod: mod1
  key: j

focus-main:
  mod: <NONE>
  key: <NONE>

focus-screen-ccw:
  mod: <NONE>
  key: <NONE>

focus-screen-cw:
  mod: <NONE>
  key: <NONE>

swap-screen-ccw:
  mod: <NONE>
  key: <NONE>

swap-screen-cw:
  mod: <NONE>
  key: <NONE>

swap-ccw:
  mod: mod2
  key: k

swap-cw:
  mod: mod2
  key: j

swap-main:
  mod: <NONE>
  key: <NONE>

select-tall-layout:
  mod: <NONE>
  key: <NONE>

select-wide-layout:
  mod: <NONE>
  key: <NONE>

select-fullscreen-layout:
  mod: <NONE>
  key: <NONE>

select-column-layout:
  mod: <NONE>
  key: <NONE>

throw-space-left:
  mod: <NONE>
  key: <NONE>

throw-space-right:
  mod: <NONE>
  key: <NONE>

toggle-float:
  mod: <NONE>
  key: <NONE>

display-current-layout:
  mod: <NONE>
  key: <NONE>

toggle-tiling:
  mod: <NONE>
  key: <NONE>

reevaluate-windows:
  mod: <NONE>
  key: <NONE>

toggle-focus-follows-mouse:
  mod: <NONE>
  key: <NONE>

relaunch-amethyst:
  mod: mod2
  key: r


focus-screen-1:
  mod: <NONE>
  key: <NONE>
focus-screen-2:
  mod: <NONE>
  key: <NONE>
focus-screen-3:
  mod: <NONE>
  key: <NONE>
focus-screen-4:
  mod: <NONE>
  key: <NONE>

throw-screen-1:
  mod: <NONE>
  key: <NONE>
throw-screen-2:
  mod: <NONE>
  key: <NONE>
throw-screen-3:
  mod: <NONE>
  key: <NONE>
throw-screen-4:
  mod: <NONE>
  key: <NONE>

throw-space-1:
  mod: <NONE>
  key: <NONE>
throw-space-2:
  mod: <NONE>
  key: <NONE>
throw-space-3:
  mod: <NONE>
  key: <NONE>
throw-space-4:
  mod: <NONE>
  key: <NONE>
throw-space-5:
  mod: <NONE>
  key: <NONE>
throw-space-6:
  mod: <NONE>
  key: <NONE>
throw-space-7:
  mod: <NONE>
  key: <NONE>
throw-space-8:
  mod: <NONE>
  key: <NONE>
throw-space-9:
  mod: <NONE>
  key: <NONE>
throw-space-10:
  mod: <NONE>
  key: <NONE>
throw-space-11:
  mod: <NONE>
  key: <NONE>
throw-space-12:
  mod: <NONE>
  key: <NONE>

select-fullscreen-layout:
  mod: <NONE>
  key: <NONE>

select-column-layout:
  mod: <NONE>
  key: <NONE>

select-wide-layout:
  mod: <NONE>
  key: <NONE>

select-tall-layout:
  mod: <NONE>
  key: <NONE>

select-wide-layout:
  mod: <NONE>
  key: <NONE>

select-fullscreen-layout:
  mod: <NONE>
  key: <NONE>

select-column-layout:
  mod: <NONE>
  key: <NONE>

disable-padding-on-builtin-display: false
window-margins: false
smart-window-margins: false
window-margin-size: 0
window-max-count: 0
window-minimum-height: 0
window-minimum-width: 0
floating: []
floating-is-blacklist: true
ignore-menu-bar: false
float-small-windows: true
mouse-follows-focus: false
focus-follows-mouse: false
mouse-swaps-windows: false
mouse-resizes-windows: false
enables-layout-hud: true
enables-layout-hud-on-space-change: true
use-canary-build: false
new-windows-to-main: false
follow-space-thrown-windows: true
window-resize-step: 5
screen-padding-left: 0
screen-padding-right: 0
screen-padding-top: 0
screen-padding-bottom: 0
restore-layouts-on-launch: true
debug-layout-info: false
